name: 'Smoke test'
description: 'Build and test a devcontainer image using the local smoke-test scripts'
inputs:
  image:
    description: 'Image to test'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3
      with:
        repository: 'tigitlabs/devcontainer'
        path: '__build'
        ref: 'main'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build image
      id: build_image
      shell: bash
      run: |
        ${{ github.action_path }}/build.sh ${{ inputs.image }}

    - name: Test image
      id: test_image
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.image }}
