name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - feat-*
  pull_request:
    branches: [dev, main]

jobs:

  markdown-check:
    name: Check Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/workflows/mlc_config.json
          file-path: ./README.md

      - name: Lint
        uses: avto-dev/markdown-lint@v1
        with:
          args: './README.md'
          config: .github/workflows/lint/markdown.yaml
