---

name: "Makefile-CI"

on:
  pull_request:
    branches: [ dev, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  makefile-sanity-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Install nectos act
        run: |
          cd /
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          act --version

      - name: Make sure the Makefile can be used
        run: make

      - name: Run make help
        run: make help

      - name: Run make github-action-list
        run: make github-action-list

      - name: Run make github-action-markdown-lint
        run: make github-action-markdown-lint

  makefile-local-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.actor }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install devcontainer cli
        run: |
          npm install -g @devcontainers/cli
          devcontainer --version

      - name: Run make build-all
        run: make build-all

      - name: Run make test-all
        run: make test-all
